baseURL = 'https://dezible.com/'
languageCode = 'en-us'
title = 'Dezible'
publishDir = "docs"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-relearn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "SEARCH"]

[params]
    alwaysopen = false
    disableToc = false
    collapsibleMenu = true
    titleSeparator = "-"