baseURL = 'https://dezible.com/'
languageCode = 'en-us'
title = 'Dezible'
publishDir = "docs"

# Change the default theme to be use when building the site with Hugo
theme = 'hugo-theme-relearn'

# For search functionality
[outputs]
home = [ "html", "rss", "search", 'searchpage']

[params]
    alwaysopen = false
    disableToc = false
    collapsibleMenu = true
    titleSeparator = "-"
    themeVariant = "dezible"
    disableLandingPageButton = true
    disableBreadcrumb = false
